name = "meilisearch"
container_type = "docker"

[image]
name = "getmeili/meilisearch"
tag = "v1.9"

[ports]
published = ["7700:7700"]

[volumes]
mounts = ["${CONFIG_PATH}/meilisearch:/meili_data"]

[environment]
MEILI_MASTER_KEY = "${MEILI_MASTER_KEY}"
